const prodcontroller=require('../controllers/product.controller')
const express=require('express')

const router=express.Router()
router.post('/addfile',prodcontroller.addfile)
router.delete('/deletefile',prodcontroller.deletefile)
router.post('/addproduct',prodcontroller.addProduct)
router.put('/updateproduct:id',prodcontroller.updateProduct)
router.put('/addcategory:name',prodcontroller.updateProduct)
router.put('/addproductphoto:id',prodcontroller.addProuctPhoto)
router.put('/deleteproductphoto:id',prodcontroller.deleteProuctPhoto)
router.put('/hitlike:id',prodcontroller.addLike)
router.put('/dislike:id',prodcontroller.adddisLike)
router.put('/unlike:id',prodcontroller.deleteLike)
router.put('/undislike:id',prodcontroller.deletedisLike)
router.delete('/deleteproduct:id',prodcontroller.deleteProduct)
router.get('/allproducts',prodcontroller.getAllProduct)
router.get('/sellerproducts',prodcontroller.getSellerProduct)
router.get('/searchproduct',prodcontroller.searchProduct)
router.get('/searchproductbyseller:seller',prodcontroller.searchProductBySeller)
router.get('/getproduct',prodcontroller.getProduct)
//router.get('/searchcategory',prodcontroller.searchCategory)
//router.get('/allcategories',prodcontroller.getAllCategories)
//router.get('/searchprice',prodcontroller.searchPrice)
module.exports=router
//router.put('/buyproduct:id',prodcontroller.buyProduct)
//router.put('/cancelbuyingproduct:id',prodcontroller.cancelBuying)
//router.put('/addcomment:id',prodcontroller.addComments)
//router.put('/deletecomment:id',prodcontroller.deleteComment)
//router.put('/giverate:id',prodcontroller.addRate)